channel.orders.name=orders_channel
channel.order_items.name=order_items_channel
pipe.orders.name=ORDERS-STREAMING
pipe.order_items.name=ORDER_ITEMS-STREAMING
max.client.lag=60
batch.size=1000
orders.batch.size=10000
num.orders.per.batch=100
max.retries=3
retry.delay.ms=1000
