# Channel names
channel.orders.name=orders_channel
channel.order_items.name=order_items_channel

# Pipe names (auto-created by Snowflake: <TABLE>-STREAMING)
pipe.orders.name=ORDERS-STREAMING
pipe.order_items.name=ORDER_ITEMS-STREAMING

# Streaming tuning
max.client.lag=60
batch.size=1000
orders.batch.size=10000
num.orders.per.batch=100

# Retry settings
max.retries=3
retry.delay.ms=1000
